version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_oslogistics
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: crm-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:latest
    container_name: crm-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
